services:
  postgresql:
    image: postgres:14-alpine3.15
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=TestLogin
      - POSTGRES_PASSWORD=08jfuhwesfkgg246j!